name: Post to Bluesky on Blog Update

on:
  repository_dispatch:
    types: [blog_post_updated]

jobs:
  post-to-bluesky:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Extract blog post metadata
        id: extract-metadata
        run: |
          # リポジトリディスパッチのペイロードから情報を取得
          title="${{ github.event.client_payload.title }}"
          description="${{ github.event.client_payload.description }}"
          url="${{ github.event.client_payload.url }}"
          author="${{ github.event.client_payload.author }}"
          tags="${{ github.event.client_payload.tags }}"
          
          echo "title=$title" >> $GITHUB_OUTPUT
          echo "description=$description" >> $GITHUB_OUTPUT  
          echo "url=$url" >> $GITHUB_OUTPUT
          echo "author=$author" >> $GITHUB_OUTPUT
          echo "tags=$tags" >> $GITHUB_OUTPUT
          
          echo "Received blog post update:"
          echo "Title: $title"
          echo "Description: $description"
          echo "URL: $url"
          echo "Author: $author"
          echo "Tags: $tags"
      
      - name: Post to Bluesky
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: |
          title="${{ steps.extract-metadata.outputs.title }}"
          description="${{ steps.extract-metadata.outputs.description }}"
          url="${{ steps.extract-metadata.outputs.url }}"
          author="${{ steps.extract-metadata.outputs.author }}"
          tags="${{ steps.extract-metadata.outputs.tags }}"
          
          # タイトルまたはURLが空の場合はスキップ
          if [ -z "$title" ] || [ -z "$url" ]; then
            echo "⚠️ タイトルまたはURLが空のため、投稿をスキップします"
            exit 0
          fi
          
          # タグがある場合はハッシュタグとして追加
          hashtags="#技術ブログ #プログラミング"
          if [ -n "$tags" ]; then
            # カンマ区切りのタグをハッシュタグに変換
            additional_tags=$(echo "$tags" | sed 's/,/ #/g' | sed 's/^/#/')
            hashtags="$hashtags $additional_tags"
          fi
          
          # 著者情報がある場合は追加
          author_text=""
          if [ -n "$author" ] && [ "$author" != "tkgstrator" ]; then
            author_text="by $author"
          fi
          
          # Blueskyの投稿文を作成（文字数制限を考慮）
          post_text="📝 新しい記事を公開しました！

${title}"
          
          # 説明があり、文字数に余裕がある場合は追加
          if [ -n "$description" ]; then
            current_length=$(echo "$post_text" | wc -c)
            description_length=$(echo "$description" | wc -c)
            if [ $((current_length + description_length + 50)) -lt 300 ]; then
              post_text="$post_text

${description}"
            fi
          fi
          
          # 著者情報を追加
          if [ -n "$author_text" ]; then
            post_text="$post_text

$author_text"
          fi
          
          # URLとハッシュタグを追加
          post_text="$post_text

${url}

$hashtags"
          
          echo "投稿内容:"
          echo "$post_text"
          echo "文字数: $(echo "$post_text" | wc -c)"
          
          # Blueskyにログインしてアクセストークンを取得
          echo "Logging in to Bluesky..."
          auth_response=$(curl -s -X POST https://bsky.social/xrpc/com.atproto.server.createSession \
            -H "Content-Type: application/json" \
            -d "{\"identifier\": \"$BLUESKY_HANDLE\", \"password\": \"$BLUESKY_PASSWORD\"}")
          
          access_token=$(echo "$auth_response" | jq -r '.accessJwt')
          did=$(echo "$auth_response" | jq -r '.did')
          
          if [ "$access_token" = "null" ] || [ "$access_token" = "" ]; then
            echo "Failed to authenticate with Bluesky"
            echo "Response: $auth_response"
            exit 1
          fi
          
          echo "Successfully authenticated. DID: $did"
          
          # JSONエスケープのための関数
          escape_json() {
            echo "$1" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g'
          }
          
          escaped_text=$(escape_json "$post_text")
          
          # 投稿を作成
          echo "Creating post..."
          post_response=$(curl -s -X POST https://bsky.social/xrpc/com.atproto.repo.createRecord \
            -H "Authorization: Bearer $access_token" \
            -H "Content-Type: application/json" \
            -d "{
              \"repo\": \"$did\",
              \"collection\": \"app.bsky.feed.post\",
              \"record\": {
                \"text\": \"$escaped_text\",
                \"createdAt\": \"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)\"
              }
            }")
          
          if echo "$post_response" | jq -e '.uri' > /dev/null; then
            echo "✅ Successfully posted to Bluesky!"
            echo "Post URI: $(echo "$post_response" | jq -r '.uri')"
          else
            echo "❌ Failed to post to Bluesky"
            echo "Response: $post_response"
            exit 1
          fi