name: Update Submodule

on:
  # 毎日午前2時（UTC）に実行
  schedule:
    - cron: '0 2 * * *'
  # 手動実行も可能
  workflow_dispatch:
  # コンテンツリポジトリからのwebhookも受け取れるように（オプション）
  repository_dispatch:
    types: [content-updated]

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          
      - name: Update submodule to latest commit
        run: |
          git submodule update --remote
          
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet HEAD src/content; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/content
          git commit -m "chore: update content submodule to latest commit"
          git push
          
      - name: Create Pull Request (alternative)
        if: steps.check_changes.outputs.changes == 'true' && false
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update content submodule to latest commit"
          title: "Update content submodule"
          body: |
            This PR automatically updates the content submodule to the latest commit.
            
            Auto-generated by GitHub Actions.
          branch: update-submodule
          delete-branch: true
